// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zstptpicdjmvjizhmfhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzdHB0cGljZGptdmppemhtZmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTY1NTIsImV4cCI6MjA1OTE3MjU1Mn0.FQbsn5jR09In7TNj1saiUeO2nn8YctEZ1HGmRBgAB5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);